### PR TITLE
update substrate to use polkadot-master branch

### PR DESCRIPTION
**Pull request by mnaamani**

### CODE REVIEW

**Review by bedeho — CHANGES_REQUESTED** [review]
Could we not depend on a branch, that just seems like an issue waiting to bite us at some point.

**Comment by mnaamani** [comment]
> Could we not depend on a branch, that just seems like an issue waiting to bite us at some point.

Yes we are depending on the branch `polkadot-master` however it is a fast moving branch. It would be better to depend on a specific commit hash that is a "known working" version. But currently the last known working version is too old and doesn't have some features that we need.

**Comment by mnaamani** [comment]
Since we have a working build today from that branch, I will select commit hash `0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3` - https://github.com/paritytech/substrate/commit/0e3001a1ad6fa3d1ba7da7342a8d0d3b3facb2f3 and update the PR.

**Comment by mnaamani** [comment]
I updated runtime PR as well.

**Pull request merged**
