### PR TITLE
Last set of dispatchables

### PR DESCRIPTION
**Pull request by bedeho**
- [x] `add_post`
- [x] `edit_post_text`
- [x] `moderate_post`

### CODE REVIEW

**Comment by siman** [comment]
I see that all 3 methods are checked (implemented).
Is this PR ready for review?

**Comment by bedeho** [comment]
No :D ,I will mark it ready when its 100% ready, I have to push a bit more stuff I think.

**Comment by bedeho** [comment]
Ok, ready, rebased now on https://github.com/Joystream/substrate-forum-module/pull/10.

**Review by siman — APPROVED** [review]
New changes look good to me :)

**Pull request merged**
